initial and final(hope so) commit
aendrevv/ma-nodejs-2021 pull request #2
Opened 2020-11-07 01:54 UTC by aendrevv

Hi there. Please feed back me. 
(:

2020-11-07 20:59 UTC, VitaliiHurin requested changes
Загалом непогано, проте зверни увагу на питання та зауваження.

2020-11-07 20:59 UTC, VitaliiHurin commented on homework-01/task/task1.js
> +const filter = (array, type, value) => {
Невелике зауваження: краще не називати функції так само як стандартні.

2020-11-07 20:59 UTC, VitaliiHurin commented on homework-01/task/task2.js
> +  let highestPrice = Number.EPSILON;
Ого, а чому тут EPSILON? 🙂

2020-11-07 20:59 UTC, VitaliiHurin commented on homework-01/task/task2.js
> +      highestPriceElement = Object.assign(element);
Можна було просто зберігати елемент в змінну, а не робити копію.

2020-11-07 20:59 UTC, VitaliiHurin commented on homework-01/task/task2.js
> +    let totalPrice = +(element.priceForPair || element.price).slice(1) * (element.quantity || 0);
Тут можна const, а не let

2020-11-07 20:59 UTC, VitaliiHurin commented on homework-01/task/task3.js
> +      });
Чому так, а не просто присвоїти нуль в quantity? 🙂

2020-11-07 20:59 UTC, VitaliiHurin commented on homework-01/task/task3.js
> +      Object.defineProperty(element, 'price', Object.getOwnPropertyDescriptor(element, 'priceForPair'));
Це занадто надлишково, краще просте присвоєння.

2020-11-07 20:59 UTC, VitaliiHurin commented on homework-01/task/task3.js
> +  return array;
Взааглі, тут малось на увазі, що треба повертати новий модфікований масив, а не модифікувати існуючий.

2020-11-10 11:46 UTC, aendrevv commented on homework-01/task/task1.js
> +const filter = (array, type, value) => {
змінив

2020-11-10 11:47 UTC, aendrevv commented on homework-01/task/task2.js
> +  let highestPrice = Number.EPSILON;
вирішив додати родзинку) змінив на 0.

2020-11-10 11:47 UTC, aendrevv commented on homework-01/task/task2.js
> +    let totalPrice = +(element.priceForPair || element.price).slice(1) * (element.quantity || 0);
+

2020-11-10 11:52 UTC, aendrevv commented on homework-01/task/task2.js
> +      highestPriceElement = Object.assign(element);
done.

2020-11-10 12:13 UTC, aendrevv commented on homework-01/task/task3.js
> +  return array;
та от знову неправильно зрозумів умову, звідси і вся ця надлишковість %)

2020-11-10 13:09 UTC, VitaliiHurin commented on homework-01/task/task3.js
> +    return elementTemplate;
Можна просто відразу
`return { 
    type: ...,
    color: ...,
....`

2020-11-10 13:09 UTC, VitaliiHurin commented
👍

2020-11-10 13:09 UTC, merged