Homework 02
aendrevv/ma-nodejs-2021 pull request #3
Opened 2020-11-10 22:56 UTC by aendrevv

2020-11-12 19:27 UTC, VitaliiHurin requested changes
Загалом дуже добре. 👍
Не робив перемикання джерела? Щоб було як по завданню: або файлу, або зі змінної.
Зверни увагу на ремарки до коду.

2020-11-12 19:27 UTC, VitaliiHurin commented on homework-02/src/app.js
> +const port = +process.env.PORT;
Можна додати ще порт за замовчуванням

2020-11-12 19:27 UTC, VitaliiHurin commented on homework-02/src/controller.js
> +    await response.write(JSON.stringify(result));
А чому тут await?

2020-11-12 19:27 UTC, VitaliiHurin commented on homework-02/src/controller.js
> +    await response.write(JSON.stringify(task02));
Тут є сенс переробити task2 з експорту виклику на експорт функції.

2020-11-12 19:27 UTC, VitaliiHurin commented on homework-02/src/router.js
> +  if (method === 'PUT' && url === '/writeNewDataToJSON') return writeNewDataToJSON(data, response);
Тут можна переробити краще під switch/case.

2020-11-12 19:27 UTC, VitaliiHurin commented on homework-02/src/controller.js
> +    fs.writeFileSync(path.resolve('./', 'products.json'), JSON.stringify(data));
Ще може додати тут базову перевірку даних, що приходять на вхід.

2020-11-12 19:28 UTC, VitaliiHurin commented on homework-02/src/router.js
> +  if (method === 'GET' && url === `/task1?field=${queryParams.field}&value=${queryParams.value}`)
Тут можна було б не формувати повністю url для порівяння, а перевіряти лише префікс.

2020-11-16 23:35 UTC, aendrevv commented on homework-02/src/router.js
> +  if (method === 'PUT' && url === '/writeNewDataToJSON') return writeNewDataToJSON(data, response);
змінив, але як на мене то краще і лаконічніше було б через іф )

2020-11-16 23:35 UTC, aendrevv commented on homework-02/src/router.js
> +  if (method === 'GET' && url === `/task1?field=${queryParams.field}&value=${queryParams.value}`)
зробив, але окремо від світч/кейс'а

2020-11-16 23:35 UTC, aendrevv commented on homework-02/src/app.js
> +const port = +process.env.PORT;
додав

2020-11-16 23:39 UTC, aendrevv commented
> Загалом дуже добре. +1
> Не робив перемикання джерела? Щоб було як по завданню: або файлу, або зі змінної.
Не робив, бо зробив жеж пункт11: 
`11. Задачою із зірочкою буде редагування JSON файлу за інструкцією https://www.codegrepper.com/code-examples/delphi/how+to+edit+local+json+files+using+node , в такому випадку пункт 10 не потрібен`

2020-11-17 07:21 UTC, aendrevv commented on homework-02/src/router.js
> +  if (method === 'GET' && url === `/task1?field=${queryParams.field}&value=${queryParams.value}`)
done.

2020-11-17 21:18 UTC, VitaliiHurin approved these changes
Я заапрувлю, але раджу зробити коректну відповідь з валідною помилкою, якщо дані не підходять.

2020-11-17 21:18 UTC, VitaliiHurin commented on homework-02/src/controller.js
> +    return JSON.parse(str) && !!str;
JSON.parse дуже "важка" операція, використовувати її просто для перевірки не раціонально

2020-11-17 21:18 UTC, VitaliiHurin commented on homework-02/src/controller.js
> +    if (isJsonString(data)) {
Краще б перевірити дані, і якщо вони не підходять то віддати коректну помилку, а не 200.

2020-11-17 21:18 UTC, VitaliiHurin commented on homework-02/src/router.js
> +    // case `/task1${/\S*/}`:
Так просто не можна. Якщо хочеш regex, то його сюди прив'язати треба коректно.

2020-11-17 21:18 UTC, merged