Homework 03
aendrevv/ma-nodejs-2021 pull request #4
Opened 2020-11-21 00:04 UTC by aendrevv

**Please review my code ASAP**

2020-11-22 20:46 UTC, VitaliiHurin requested changes
З колбеками взагалі не правильно зроблено, а з промісами і async/await не відрізняється взагалі, хоча має бути чітке використання промісів. І ще функції для робити з промісами і async/await мають бути зроблені як обгортки для функції з колбеком.

2020-11-22 20:46 UTC, VitaliiHurin commented on homework-03/src/controller.js
> +    fs.writeFileSync(path.resolve('./', 'products.json'), JSON.stringify(data));
Знову нема перевірки даних? 👎

2020-11-22 20:46 UTC, VitaliiHurin commented on homework-03/src/router.js
> +      if (method === 'GET' && queryParams.field === 'promise') await blackFridayPromise(response);
Чому blackFridayCallback тут без await якщо це async функція?

2020-11-22 20:46 UTC, VitaliiHurin commented on homework-03/task/discount.js
> +    if (error) getDiscountCallback();
Тут не правильно. Якщо виникла помилка, то куди піде результат наступної спроби?

2020-11-22 20:46 UTC, VitaliiHurin commented on homework-03/task/discount.js
> +};
По завданню треба було зробити обгортку.

2020-11-22 20:46 UTC, VitaliiHurin commented on homework-03/task/discount.js
> +};
Щось функція для промісів, а виконуються вони через async/await... 🙂

2020-11-22 20:46 UTC, VitaliiHurin commented on homework-03/task/discount.js
> +};
Щось тут теж не видно промісів... Взагалі така сама функція як setDiscountAsync?

2020-11-22 20:46 UTC, VitaliiHurin commented on homework-03/task/discount.js
> +};
А де ж тут колбеки? Не правильно, воно не працюватиме так, як я і вказав в коментарі до функції getDiscountCallback.

2020-11-22 20:46 UTC, VitaliiHurin commented on homework-03/task/myMap.js
> +      returningArray[k] = callback.call(thisArg, array[k], k, array);
Звідки береться тут thisArg?
Для чого тут взагалі function.call()?

2020-11-24 00:22 UTC, aendrevv commented on homework-03/src/controller.js
> +    fs.writeFileSync(path.resolve('./', 'products.json'), JSON.stringify(data));
додав.

2020-11-24 00:23 UTC, aendrevv commented on homework-03/src/router.js
> +      if (method === 'GET' && queryParams.field === 'promise') await blackFridayPromise(response);
+

2020-11-24 00:24 UTC, aendrevv commented on homework-03/task/discount.js
> +    if (error) getDiscountCallback();
переробив

2020-11-24 00:27 UTC, aendrevv commented on homework-03/task/myMap.js
> +      returningArray[k] = callback.call(thisArg, array[k], k, array);
виправив

2020-11-24 00:28 UTC, aendrevv commented on homework-03/task/discount.js
> +};
повністю переробив.

2020-11-24 13:15 UTC, VitaliiHurin requested changes
У висновку бачу, що дуже багато запоплення async/await. Я розумію, що так зручно, але воно щось вилазить і в реалізації на колбеках і на звичайних промісах. 🙂

2020-11-24 13:15 UTC, VitaliiHurin commented on homework-03/src/controller.js
>  const writeNewDataToJSON = async (data, response) => {
Async тут не треба.

2020-11-24 13:15 UTC, VitaliiHurin commented on homework-03/src/controller.js
>      store = await setDiscountCallback(products);
Це ж не функція на колбеках 😔

2020-11-24 13:15 UTC, VitaliiHurin commented on homework-03/src/controller.js
>      store = await setDiscountPromise(products);
Це ж не використання через проміс 😔

2020-11-24 13:15 UTC, VitaliiHurin commented on homework-03/task/discount.js
> +    .catch(() => getDiscountPromise(discountNumber, discountValues, callback));
Щось getDiscountPromise а все одно з колбеком працює (останній параметр) 🙂

2020-11-24 13:15 UTC, VitaliiHurin commented on homework-03/task/myMap.js
> +const myMap = async (array, callback) => {
А чому myMap async функція? Це ж не є тоді повторенням функціоналу звичайного map

2020-11-25 10:17 UTC, aendrevv commented on homework-03/task/myMap.js
> +const myMap = async (array, callback) => {
виправив

2020-11-25 10:17 UTC, aendrevv commented on homework-03/task/discount.js
> +    .catch(() => getDiscountPromise(discountNumber, discountValues, callback));
переробив

2020-11-25 10:17 UTC, aendrevv commented on homework-03/src/controller.js
>      store = await setDiscountPromise(products);
переробив

2020-11-25 10:18 UTC, aendrevv commented on homework-03/src/controller.js
>  const writeNewDataToJSON = async (data, response) => {
прибрав

2020-11-25 10:54 UTC, VitaliiHurin requested changes
Не робить щось на промісах взагалі. 😔
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/12820903/100218361-544fb900-2f1d-11eb-98d4-405390714b77.png">

2020-11-25 11:25 UTC, aendrevv commented on homework-03/src/controller.js
>      store = await setDiscountCallback(products);
переробив на колбеках)

2020-11-25 12:06 UTC, aendrevv commented
> Не робить щось на промісах взагалі. pensive

Ура! Нарешті все працює так як треба!

2020-11-25 20:48 UTC, merged