Homework 04
aendrevv/ma-nodejs-2021 pull request #5
Opened 2020-12-02 03:27 UTC by aendrevv

Зроблено пункти 1, 2, 3.

2020-12-06 21:33 UTC, VitaliiHurin requested changes
При завантаженні файлу падає помилка, хоч файл і створюється:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/12820903/101292955-5cf89700-381b-11eb-893a-84bd763fabaf.png">

2020-12-06 21:33 UTC, VitaliiHurin commented on src/server/index.js
> +      callback();
Тут можна додати прокидування помилки в колбек

2020-12-06 21:33 UTC, VitaliiHurin commented on src/server/controller.js
> +    const files = await fs.promises.readdir('upload/', { withFileTypes: true });
Шляхи до папок можна винести в конфіг чи просто в константу.

2020-12-06 21:33 UTC, VitaliiHurin commented on src/server/controller.js
> +  const filepath = `upload/${id}.json`;
Шляхи до папок можна винести в конфіг чи просто в константу.

2020-12-07 18:20 UTC, aendrevv commented on src/server/controller.js
> +  const filepath = `upload/${id}.json`;
виніс у конфіг.

2020-12-07 18:21 UTC, aendrevv commented on src/server/index.js
> +      callback();
зробив

2020-12-07 18:21 UTC, aendrevv commented
> При завантаженні файлу падає помилка, хоч файл і створюється:

Виправив.
![image](https://user-images.githubusercontent.com/55597337/101389233-cb942e00-38c9-11eb-8a98-01b3c8a095d1.png)

2020-12-07 22:44 UTC, VitaliiHurin requested changes
Помилка залишається:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/12820903/101414334-8f26f900-38ee-11eb-9e64-f5bc2fc1be1b.png">

2020-12-07 22:44 UTC, VitaliiHurin commented on src/server/controller.js
> +  const filepath = `${UPLOAD}${id}.json`;
Тут би ще все обернути через модуль path, а не просто в купу з'єднати.

2020-12-07 22:44 UTC, VitaliiHurin commented on src/server/controller.js
> +    await fs.promises.mkdir(UPLOAD, { recursive: true });
Тут так само зарезолвити шлях через модуль path не завадило б.

2020-12-07 22:44 UTC, VitaliiHurin commented on src/server/controller.js
> +    const files = await fs.promises.readdir(UPLOAD, { withFileTypes: true });
Тут так само зарезолвити шлях через модуль path не завадило б.

2020-12-08 20:38 UTC, merged